img_proces.cpp
const int ROWS
variable which defines size of cropped images
Referenced by thumbnails_matrix.
const int COLS
variable which defines size of cropped images
Referenced by thumbnails_matrix.
vector<Mat> Image
vector of images to process
Referenced by edge_detecting, img_read, img_write, main, multithread, read_input_folder_info.
vector<Mat> ImageColor
vector of loaded coloured images
Referenced by img_read, main, read_input_folder_info.
vector<String> filenames
vector of loaded images names
Referenced by img_read, read_input_folder_info, thumbnails_matrix.
void read_input_folder_info()
function to read info of images to process
References dir_img, filenames, Image, ImageColor, dir::input.
Referenced by main.
void img_read(int img_index)
reads one image from source folder
References filenames, Image, ImageColor.
Referenced by Work.
void img_write(int img_index)
writes one processed image to destination folder
References dir_img, Image, dir::output.
Referenced by Work.
void edge_detecting(int img_index)
edge detecting function based on laplacian detection, processes singular image
References Image.
Referenced by Work.
void thumbnails_matrix(string file_name, vector< Mat > ImagesToConcatanate)
creates matrix of thumbnails of given images
References COLS, dir_img, filenames, dir::output, ROWS.
Referenced by main.