img_proces.h
vector<Mat> Image
vector of images to process
Referenced by edge_detecting, img_read, img_write, main, multithread, read_input_folder_info.
vector<Mat> ImageColor
vector of loaded coloured images
Referenced by img_read, main, read_input_folder_info.
void read_input_folder_info()
function to read info of images to process
References dir_img, filenames, Image, ImageColor, dir::input.
Referenced by main.
void img_read(int)
reads one image from source folder
References filenames, Image, ImageColor.
Referenced by Work.
void img_write(int)
writes one processed image to destination folder
References dir_img, Image, dir::output.
Referenced by Work.
void edge_detecting(int)
edge detecting function based on laplacian detection, processes singular image
References Image.
Referenced by Work.
void thumbnails_matrix(string, vector< Mat >)
creates matrix of thumbnails of given images
References COLS, dir_img, filenames, dir::output, ROWS.
Referenced by main.