ini_parser.cpp
struct dir dir_img
global variable of directories of input and output dir
Referenced by img_write, ini_read, read_input_folder_info, thumbnails_matrix.
char * get_dir()
Referenced by ini_read.
bool check_dir(char *dir)
Referenced by ini_read.
int ini_read()
reads initialization file
References check_dir, dir_img, get_dir, dir::input, dir::output.
Referenced by main.